name: ci
on:
  push:
    branches:
      - main
      - +([0-9])?(.{+([0-9]),x}).x
  pull_request:

jobs:
  main:
    name: Tests
    runs-on: ubuntu-latest
    container: ghcr.io/spaceship-prompt/spaceship-prompt:latest
    steps:
      - name: ⬇️ Checkout Repo
        uses: actions/checkout@v2

      - name: 🖨 Print Zsh Version
        run: zsh --version

      - name: 🧪 Run Tests
        run: ./tests/spaceship-section.test.zsh

  release:
    name: Release
    needs: main
    if: ${{ github.repository == 'spaceship-prompt/spaceship-section' && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout Repo
        uses: actions/checkout@v2

      - name: 🚀 Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            semantic-release-license
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  with:
    repository: nano-sudor-sh/-nano
    token: ***
    ssh-strict: true
    persist-credentials: true
    clean: true
    fetch-depth: 1
    lfs: false
    submodules: false
    set-safe-directory: true
/usr/bin/docker exec  2193de6dc679598b98f28b2d4dcf991deec487f35497294cfc57fc4e58dabfc1 sh -c "cat /etc/*release | grep ^ID"
Error relocating /__e/node20_alpine/bin/node: sched_getcpu: symbol not found
Error relocating /__e/node20_alpine/bin/node: getrandom: symbol not found
Error relocating /__e/node20_alpine/bin/node: getentropy: symbol not found
Error relocating /__e/node20_alpine/bin/node: secure_getenv: symbol not found
0s
0s
1s
Post job cleanup.
/usr/bin/docker exec  2193de6dc679598b98f28b2d4dcf991deec487f35497294cfc57fc4e58dabfc1 sh -c "cat /etc/*release | grep ^ID"
Error relocating /__e/node20_alpine/bin/node: sched_getcpu: symbol not found
Error relocating /__e/node20_alpine/bin/node: getrandom: symbol not found
Error relocating /__e/node20_alpine/bin/node: getentropy: symbol not found
Error relocating /__e/node20_alpine/bin/node: secure_getenv: symbol not found
0s
0s
Cleaning up orphan processes

          
